#!/usr/bin/env bash

cmd_help(){
    local script_path=`dirname $(realpath $0)`
    if man 1 carp &>/dev/null; then
        man 1 carp

    elif [ -f "${script_path}/carp.1" ]; then
        man -l "${script_path}/carp.1"

    else
      echo "No manual found :("
    fi
}

cmd_init(){
    FOLDER_NAME=`basename $1`
    PRIVATE_FOLDER="$HOME/Private/$FOLDER_NAME"
    PREFPATH="$HOME/.config/.carp/$FOLDER_NAME"

    if [ ! -d "$PRIVATE_FOLDER" ]; then
        mkdir -p "$PRIVATE_FOLDER"
    fi

    if [ ! -d "$PREFPATH" ]; then
        mkdir -p "$PREFPATH"
    fi

    PASSWORD_FILE="${PREFPATH}/encfs.pass"
}


cmd_list(){
    grep Private /etc/mtab | sed -n "s|encfs $HOME/Private/\(.*\) fuse\.encfs.*|\1|p"
}


cmd_mount(){
    if [ ! -n "$1" ]; then
        cmd_help 'mount'
        exit 1
    fi

    cmd_init "$1"

    if grep -q "$PRIVATE_FOLDER" /etc/mtab; then
        echo "$FOLDER_NAME already mounted"
        exit 1
    fi

    if [ ! -f "${PREFPATH}/encfs6.xml" ]; then
        echo "No preference file found for $FOLDER_NAME"
        exit 1
    fi

    export ENCFS6_CONFIG="${PREFPATH}/encfs6.xml"
    if [ -f "$PASSWORD_FILE" ]; then
        cat "$PASSWORD_FILE" | encfs -S "$1" "$PRIVATE_FOLDER"
    else
        encfs "$1" "$PRIVATE_FOLDER"
    fi

    if [ "$?" = 0 ]; then
        echo "$FOLDER_NAME mounted"
    else
        echo "$FOLDER_NAME NOT mounted"
    fi
}

cmd_umount(){
    if [ ! -n "$1" ]; then
        cmd_help 'umount'
        exit 1
    fi

    local FOLDER_NAME="$1"
    local PRIVATE_FOLDER="$HOME/Private/$FOLDER_NAME"

    if grep -q "$PRIVATE_FOLDER" /etc/mtab; then
        if fusermount -u "$PRIVATE_FOLDER"; then
            echo "$FOLDER_NAME unmounted"
        else
            echo "An error happened, $FOLDER_NAME NOT unmounted"
        fi
    else
        echo "$FOLDER_NAME does not seem to be mounted"
    fi
}

cmd_create(){
    if [ ! -n "$1" ]; then
        cmd_help 'create'
        exit 1
    fi

    local MUST_SAVE_PASSWORD=1
    local MUST_MOUNT_AFTER_CREATE=1
    while getopts  "sm" flag; do
        case "$flag" in
            s) MUST_SAVE_PASSWORD=0 ;;
            m) MUST_MOUNT_AFTER_CREATE=0 ;;
        esac
    done
    shift $((OPTIND-1))

    if [ ! -d "$1" ]; then
       mkdir -p "$1"
    fi

    cmd_init "$1"

    if [ -d "$PRIVATE_FOLDER" ]; then
        echo "Warning: $PRIVATE_FOLDER already exists in the file system. Encfs creation will probably fail. Please remove/rename it first."
        exit 1
    fi

    encfs "$1" "$PRIVATE_FOLDER"
    sleep 2
    fusermount -u "$PRIVATE_FOLDER"

    mv "$1/.encfs6.xml" "${PREFPATH}/encfs6.xml"

    if [ "$MUST_SAVE_PASSWORD" = 0 ]; then
        echo "Please enter your password a last time in order to save it in your home folder. Leave it blank and press enter if you changed your mind."
        echo -n "Password > "
        read PASSWORD

        if [ -n "$PASSWORD" ]; then
            echo "$PASSWORD" > "$PASSWORD_FILE"
        fi
    fi

    echo "Secret folder created"

    if [ "$MUST_MOUNT_AFTER_CREATE" = 0 ]; then
        cmd_mount "$1"
    fi
}

if [ ! -d "$HOME/.config/.carp" ]; then
    mkdir -p "$HOME/.config/.carp"
fi

if [ ! -d "$HOME/Private" ]; then
    mkdir -p "$HOME/Private"
fi

case "$1" in
    create) shift; cmd_create "$@" ;;
    mount|merveilleux) shift; cmd_mount "$@" ;;
    umount|regretté) shift; cmd_umount "$@" ;;
    list) shift; cmd_list ;;
    *) cmd_help ;;
esac
