.TH CARP 1 "30 novembre 2016"
.SH NAME
carp - EncFS CLI managing tool
.SH SYNOPSIS
.B carp
[\fB\-c\fR]
.B create
[\fB\-m\fR] [\fB\-s\fR]
.I rootdir
.LP
.B carp
[\fB\-c\fR]
[ \fBmount\fR | \fBunmount\fR | \fBpull\fR | \fBpush\fR ]
[\fB\-t\fR]
.I name
.LP
.B carp
[\fB\-c\fR]
.B list
[ mounted | unmounted | all ]
.LP
.B carp
[--help]
.SH DESCRIPTION
carp is an EncFS frontend to ease day-to-day creating, mounting and
unmounting your various stashes. Using this script, your stash will
always be mounted under \fI~/Private\fR.
.SH COMMANDS
.TP
.B create
Create a new EncFS stash.
.TP
.B mount
Mount an existing EncFS stash.
.TP
.B unmount
Unmount a currently mounted EncFS stash.
.TP
.B list
List your EncFS stashes. You can list only mounted or unmounted stash,
or both. Default is to show mounted stashes.
.SH "OPTIONS"
.TP
.B -c
Alternate path to a config file.
.TP
.B --help
Show an help message. All commands have their own help pages, accessible
through \fBpath command --help\fR. For exemple:
.B "carp create --help"
.SH "CREATE OPTIONS"
.TP
.B -m
Automount your new encfs folder after creation
.TP
.B -s
Save your password in your home folder to avoid typing it when mounting
your secret folder.
.TP
.I rootdir
The
.B path
to your future encrypted stash. This \fBpath\fR MUST be a complete path,
not a relative one.
.SH "MOUNT, UNMOUNT, PULL AND PUSH OPTIONS"
.TP
.B -t
Do not actually do the action asked. For \fBpull\fR and \fBpush\fR it
will lead to a dry-run of rsync. For \fBmount\fR and \fBunmount\fR it
will only check if the required directories are in place.
.TP
.I name
The
.B name
of one of your EncFS stashes. You can find these names by using the
\fIcarp\fR \fBlist\fR command.
.SH FILES
.LP
~/.config/.carp/config - General config file.
.LP
~/.config/.carp/* - Each subfolder contains the stash-related
configuration file and your \fBnot-encrypted\fR passphrase in another
file.
.LP
~/Private - All your EncFS stash will be mounted under the \fIPrivate\fR
folder of the current user home folder.
.SH "SEE ALSO"
.BR encfs (1),
.BR fusermount (1).
.SH AUTHOR
Étienne Deparis <etienne@depar.is>
