#+title: CARP
#+date: <2015-09-10 jeu.>

* NAME
carp - EncFS CLI managing tool

Main development occurs here: https://projects.depar.is/carp/ That's
here you must create tickets if you find some bugs. However, pull
request could be pushed to github too.

* SYNOPSIS

*carp create* [ *-m* ] [ *-s* ]

*carp mount* /rootdir/

*carp umount* /name/

*carp* [ *help* | *list* ]

* DESCRIPTION

carp is an EncFS frontend to ease day-to-day creating, mounting and
umounting your various stashes. Using this script, your stash will
always be mounted under /~/Private/.

* COMMANDS

 - create :: Create a new EncFS stash.
 - mount :: Mount an existing EncFS stash.
 - umount :: Umount a currently mounted EncFS stash.
 - list :: List all your currently mounted EncFS stashes.
 - help :: Show this manual page.

* CREATE OPTIONS

 - -m :: Automount your new encfs folder after creation
 - -s :: Save your password in your home folder to avoid typing it when
      mounting your secret folder.
 - /rootdir/ :: The *path* to your future encrypted stash. This *path*
      MUST be a complete path, not a relative one.

* MOUNT OPTIONS

 - /rootdir/ :: The *path* to the encrypted stash you want to open. This
      *path* MUST be a complete path, not a relative one.

* UMOUNT OPTIONS

 - /name/ :: The *name* of one of your currently mounted EncFS
      stash. You can find these names by using the /carp/ *list*
      command.

* FILES

~/.config/.carp/* - Each subfolder contains the stash-related
configuration file and your *not-encrypted* passphrase in another
file.

~/Private - All your EncFS stash will be mounted under the /Private/
folder of the current user home folder.
