#+title: CARP
#+date: <2015-09-10 jeu.>

* NAME
carp - EncFS CLI managing tool

Main development occurs here: https://projects.depar.is/carp/ That's
here you must create tickets if you find some bugs. However, pull
request could be pushed to github too.

* SYNOPSIS

*carp* [ *-c* ] *create* [ *-m* ] [ *-s* ] /rootdir/

*carp* [ *-c* ] [ *mount* | *unmount* | *pull* | *push* ] /name/

*carp* [ *-c* ] *list* [ *mounted* | *unmounted* | *all* ]

*carp* [--help]

* DESCRIPTION

carp is an EncFS frontend to ease day-to-day creating, mounting and
umounting your various stashes. Using this script, your stash will
always be mounted under /~/Private/.

* COMMANDS

 - create :: Create a new EncFS stash.
 - mount :: Mount an existing EncFS stash.
 - umount :: Umount a currently mounted EncFS stash.
 - pull :: Pull a distant stash.
 - push :: Push to a distant stash.
 - list :: List all your currently mounted EncFS stashes.

* OPTIONS

 - -c :: Alternate path to a config file.
 - --help :: Show an help message. All commands have their own help
      pages, accessible through *carp command --help*. For exemple:
      *carp create --help*

** CREATE OPTIONS

 - -m :: Automount your new encfs folder after creation
 - -s :: Save your password in your home folder to avoid typing it when
      mounting your secret folder.
 - /rootdir/ :: The path to your future encrypted stash. This path MUST
      be a complete path, not a relative one.

** MOUNT, UNMOUNT, PULL AND PUSH OPTIONS

 - -t :: Do not actually do the action asked. For *pull* and *push* it
      will lead to a dry-run of rsync. For *mount* and *unmount* it will
      only check if the required directories are in place.
 - /name/ :: The name of one of your EncFS stash. You can find these
      names by using the *carp list* command.

* FILES

~/.config/.carp/carp.conf - Default config file (if *-c* option is not
provided). It will be created if it does not exists. Only stash listed
in there are taken into account.

~/.config/.carp/* - Each subfolder contains the stash-related
configuration file and your encrypted passphrase if you chose to save
it.

~/Private - All your EncFS stash will be mounted under the /Private/
folder of the current user home folder.

#+begin_man
.SH SEE ALSO
.BR carp.conf (5),
.BR encfs (1),
.BR fusermount (1).

.SH AUTHOR
Étienne Deparis <etienne@depar.is>
#+end_man
